default: jeuxsms
connections:
    hosty:
        driver: mysql
        host: 127.0.0.1
        database: jeuxsms_db
        username: root
        password:
        charset: utf8
        collation: utf8_general_ci
        prefix: jxs_
 